services:
  app:
    build: .
    container_name: pmc-exam-app
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: pmc-exam-web
    restart: always
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: pmc-exam-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: uQPFVu(Oyfa3a[H5
      MYSQL_DATABASE: pmc-exam
      MYSQL_USER: pmc-exam
      MYSQL_PASSWORD: uQPFVu(Oyfa3a[H5
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
